### ISSUE TITLE
Odd network behaviors?

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/hyperdrive#114]
This may not be the right repo for this, but it spans a few different modules so I figured this would work.

I logged some network traffic and wrote some notes (in C-style comments) here: https://gist.github.com/pfrazee/254010f5185beca6091c2f2340dbe51a

Here's the odd bits:

---

## Archive-bot connects to me once every five seconds

You can see these connections multiple times in the log, and it almost always plays out the same way. Should archive-bot be connecting that often? Should archive-bot be requesting data every time? Should the connection be closed locally, not by archive-bot, every time? What's going on there?

---

## A bunch of peers discovered via DHT, but not connected to?

If you search for `that's unusual, 0ff7d..cd is not an interesting archive`, you'll find a section where 7 peers are discovered via the DHT for an archive that I don't think any of them should know about. (You can map archive key -> discovery key by looking at the very top segment's initial announcements.)

None of those discoveries lead to connection attempts. What could that be?

---

## Some redundant activity

All of the activity in this log occurred in less than 2 minutes. It settles down after about a minute, but the local node's IP is discovered a whole lot. If you search for `everything is emitting twice`, you'll notice a lot of duplicate dns discovery emits early on. Not sure if any of that's an issue (the duplicate dns emits seem a little weird.)

**Comment by mafintosh** [comment]
lots of things improved in 8 in regards to replication. feel free to reopen if still relevant
