### ISSUE TITLE
hyperdrive over mdns

### ISSUE THREAD

**Issue by luandro** [mafintosh/hyperdrive#119]
I've tried asking in [dat's repo](https://github.com/datproject/dat/issues/586) with no luck, so I'll try here. Can I use hyperdrive over multicast dns (bonjour, zero conf) to sync data between a server and mobile clients?

**Comment by pfrazee** [comment]
Dat does use multicast udp to announce peers on the local network. It
should work.

You won't be able to do mobile clients until we have Dat implemented on
mobile devices

**Comment by luandro** [comment]
Got it, thanks.

**Comment by pfrazee** [comment]
@luandro if you have a particular interest in mobile, it's as you say in the other issue: Dat's in JS. It's in the realm of possibility. But you'll be pioneering a bit.

**Comment by luandro** [comment]
@pfrazee I'm trying to get some free time to experiment next year, I'm hoping to have a chance to do such pioneer work.

I'll keep studying how hyperdrive and everything fits together in order to understand what is doable. I'm still very new to p2p networking, so if you have any essential resources to point out, it would deff help out a lot.

**Comment by pfrazee** [comment]
https://github.com/datproject/awesome-dat/ is a pretty good resource for dat. I think your biggest first challenge for mobile will be just getting the toolchain to compile for the target platform, and have the needed access to APIs

**Comment by luandro** [comment]
Hey @pfrazee, could you point me out access to what API's would be needed?

**Comment by pfrazee** [comment]
Yeah, check out https://github.com/datproject/dat-node
