### ISSUE TITLE
How about encrypted connection and peer authentication?

### ISSUE THREAD

**Issue by green-coder** [mafintosh/hyperdrive#13]
I tried to read as much as I could, but I saw nowhere anything related to peer-to-peer connections being authenticated and encrypted. It looks like as now hyperdrive has no security at all. Did I miss something or it is not in the scope of hyperdrive?

If somebody wants to have authentication and encryption of the connections, which npm module and public/private key system would you recommend?

**Comment by karissa** [comment]
+1 we've been thinking about this too. We don't really have the capacity or expertise in our current team, so hopefully we will be able to grab some cash to hire a team to work on this full time or will be able to work with another group.

**Comment by maxogden** [comment]
At a technical level I think the general idea is to make hyperdrive compatible with anything that has "swarm-like" interface. Right now it composes together with discovery-channel, and @mafintosh is working on a thing similar to discovery-channel but for the actual data transfer. So if someone writes an encrypted swarm they should be able to use it with hyperdrive.

**Comment by mafintosh** [comment]
The technical paper has a big section on content integrity which relates to how you trust data from untrusted peers. Hyperdrive itself doesn't make any assumptions about transport streams. That being said if someone writes an end-to-end encrypted swarm it should interop nicely.
