### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by substack** [mafintosh/hyperdrive#166]
I've almost got hyperdrive running in the browser using [random-access-idb][1]. However, hyperdrive calls crypto_kdf_derive_from_key which is [not supported in sodium-javascript][2].

[1]: https://npmjs.com/package/random-access-idb
[2]: https://github.com/sodium-friends/sodium-javascript/issues/2

**Comment by millette** [comment]
Ping - fixed upstream, yay!

**Comment by DouglasMeyer** [comment]
It looks like hyperdrive isn't working in the browser again. I'm fairly new to this tech stack, but http://karissa.github.io/hyperdrive-ui and dat both seem to not work. I'm trying to find a simple example, but this is what I've got so far: https://jsfiddle.net/Douglas_Meyer/5kn8rxwb/2/

Thanks for your help.

**Comment by karissa** [comment]
Have you tried dat-ja?

**Comment by DouglasMeyer** [comment]
The jsfiddle I lined to uses the 6.2.0 build of dat-js, and (from what I could gather) that pointed me to here as the source of the problem. I could be wrong in my use of dat-js or hyperdrive; so any help would be appreciated. Thanks!

**Comment by substack** [comment]
Not sure about other people's issues, but for my own purposes hyperdrive works in the browser now using random-access-idb.

**Comment by karissa** [comment]
@substack do you have an example of it somewhere that you can share with everyone? thanks!

**Comment by aral** [comment]
@substack I’d also appreciate it if there is an example. Dat-js is deprecated and I’m finding it difficult to find a getting started path for using hypercore/hyperdb/hyperdrive universally (from Node.js and browser).

**Comment by RangerMauve** [comment]
@aral I've got hyperdrive working with random-access-idb in my [demo for dat-archive-web](https://github.com/RangerMauve/dat-archive-web/blob/gh-pages/demo.js).

If you want it to be "universal", you should choose a storage for node, then alias that storage to `random-access-idb` in your package.json `browser` field with browserify, or using whatever aliasing you'd use in webpack/babel if you're using that.

**Comment by aral** [comment]
@RangerMauve Thanks, I appreciate it! Will check it out :)
