### ISSUE TITLE
more docs

### ISSUE THREAD

**Issue by ralphtheninja** [mafintosh/hyperdrive#178]

**Comment by jwerle** [comment]
please and ty

**Comment by yoshuawuyts** [comment]
@ralphtheninja what are you missing? More API docs, or more examples or..?

**Comment by ralphtheninja** [comment]
@yoshuawuyts I created this issue just as a reminder because @mafintosh said more docs was needed. At a quick glance I don't see `key` documented and I think there are some properties of the `options` object that aren't documented
