### ISSUE TITLE
put options for archive.content hypercore in one place

### ISSUE THREAD

**Issue by joehand** [mafintosh/hyperdrive#181]
There are two places we set options for `archive.content` before creating the hypercore feed.

1. https://github.com/mafintosh/hyperdrive/blob/master/index.js#L672-L678
2. https://github.com/mafintosh/hyperdrive/blob/master/index.js#L718-L723

Seems like a bug waiting to happen. Already one of the options, `opts.maxRequests`, is getting passed through in one situation but not the other.

We should put them together somewhere.

**Comment by ralphtheninja** [comment]
`sparse` is also set differently, one favors `self.latest` over `self.sparse`.
