### ISSUE TITLE
9.5.0 breaks expected behavior for sparse hyperdrives 

### ISSUE THREAD

**Issue by sdockray** [mafintosh/hyperdrive#188]
Prior to 9.5.0, the sparse opt would mean sparse content but metadata was downloaded. Since 9.5.0, a sparse hyperdrive (and sparse dat as in the gist below) is sparse for both feeds.

https://gist.github.com/sdockray/f65730586135fa310ff5d4e17c25d884

I suppose that resolving this would mean:
a) sparse setting could be something other than boolean
or) sparse could refer to content and a new option for sparseMetadata
b) I now need to take an additional step to prompt hyperdrive to download all the metadata when in sparse: `archive.metadata.download()`

Not sure which makes the most sense, but if it's b then we should add it to README i think

**Comment by mafintosh** [comment]
Ya I agree, we should revert this and make a new option sparseMetadata that defaults to false and then you set both to true to enable "super" sparse mode. 

You up for sending me a PR that does that so we can get it fixed?

**Comment by creationix** [comment]
This can be closed now right?

**Comment by mafintosh** [comment]
Yea 👍
