### ISSUE TITLE
crash on feed access

### ISSUE THREAD

**Issue by maxogden** [mafintosh/hyperdrive#2]
when we asked for `feed.get` for an index that didnt exist:

```
undefined:5
  if (!end) end = buf.length
                     ^

TypeError: Cannot read property 'length' of null
    at Object.decode (eval at <anonymous> (/Users/max/src/js/hyperdrive/node_modules/protocol-buffers/node_modules/generate-function/index.js:55:21), <anonymous>:5:22)
    at /Users/max/src/js/hyperdrive/lib/feed.js:61:32
    at /Users/max/src/js/hyperdrive/lib/feed.js:42:71
    at apply (/Users/max/src/js/hyperdrive/node_modules/thunky/index.js:16:28)
    at Feed.open (/Users/max/src/js/hyperdrive/node_modules/thunky/index.js:27:3)
    at Feed.get (/Users/max/src/js/hyperdrive/lib/feed.js:41:8)
    at downloadNext (/Users/max/src/js/dat/index.js:106:10)
    at /Users/max/src/js/dat/index.js:127:9
    at done (/Users/max/src/js/run-series/index.js:11:7)
    at Object.cb (/Users/max/src/js/dat/index.js:117:15)
```

**Comment by maxogden** [comment]
@mafintosh whats the recommended way to get all feed items with `feed.get`? e.g. how do you know how many feed items there are? right now im doing this https://github.com/maxogden/dat/blob/1.0/index.js#L102-L107

because I couldnt see any other way to know what all the feed entries are

**Comment by mafintosh** [comment]
its not documented yet (working on it) but the feed size is known when the first block is received (doesn't matter which index).

It's gonna be exposed as `feed.blocks` and I'm gonna make `feed.get(index, cb)` call the callback with `(null, null)` if you call it with an `index >= feed.blocks`

**Comment by mafintosh** [comment]
hyperdrive 1.1.0 supports this now. I've also added a `.ready(cb)` method to the feeds that guarantees that `feed.blocks` have been populated after the callback has been called for convenience.

i'm thinking i should add a `feed.createStream()` method as well since that could prioritise blocks in the stream for you similar to how peerflix works.

**Comment by maxogden** [comment]
@mafintosh @karissa and I were wondering if you were gonna do a stream interface. currently fetch blocks in series https://github.com/maxogden/dat/blob/9fc1d9eb2abdf07b3729e4c59fd12d894af21c98/index.js#L105 but some level of parallelism would be better (as long as you can buffer the ones that come in out of order in memory until its their turn to be written). If you can come up with a good abstraction that lets you set the paralellism i think it is fine to put a block stream into hyperdrive

**Comment by mafintosh** [comment]
I'm gonna make hyperdrive write to all blocks to disk using a storage abstraction you can pass in. Thats gonna solve any buffering issues.
