### ISSUE TITLE
Hyperdrive crashes trying to get empty files

### ISSUE THREAD

**Issue by paulkernfeld** [mafintosh/hyperdrive#20]
This means that a `dat` clone operation will fail if the directory to be cloned includes any empty files. They can be written, but not read. Probably this is worth fixing, since empty files can be useful in some situations.

I added a [failing test](https://github.com/paulkernfeld/hyperdrive/blob/get-empty-files/test/feeds.js) that illustrates this problem.

**Comment by mafintosh** [comment]
Empty files will have an empty `link` property. See the "add empty file" test.

**Comment by mafintosh** [comment]
did dat crash trying to clone an empty file?

**Comment by mafintosh** [comment]
(Closed this because empty files are working in hyperdrive. Still curious to hear where you experienced the problem)

**Comment by paulkernfeld** [comment]
Ah, okay, I was jumping to conclusions. I made a better issue, [dat 431](https://github.com/maxogden/dat/issues/431).
