### ISSUE TITLE
usage: what is origKey?

### ISSUE THREAD

**Issue by ZhouHansen** [mafintosh/hyperdrive#225]
I want to try out the usage example in README.md. But I don't know how to set `origKey`. So it gives me errors: `Error: First shared hypercore must be the same.` or `Error: Another hypercore is stored here`

**Comment by austinfrey** [comment]
@ZhouHansen the `origKey` is the public key of the `hyperdrive` archive you are trying to replicate, you can find it by doing something like this...
```js
const drive = hyperdrive('some-drive')
drive.ready(() => {
    console.log(drive.key.toString('hex')) // will print key 0e9d0dc7fb......e33adb61338
    
    // do replication stuff
})
```

when you want to replicate/clone the drive you can supply it to your new drive instance
```js
// on new machine somewhere supply the original public key
const key = '0e9d0dc7fb79...1bd31baefe33adb61338'
const drive = hyperdrive('cloned-drive', key)

// do the replication stuff
```
is that helpful?

**Comment by austinfrey** [comment]
@ZhouHansen it should work on the same machine, but might need to have two directories setup. in the directory that you are replicating the drive to, is there a hyperdrive instance still stored there? if so, I'd remove it and start fresh in that directory.

**Comment by ZhouHansen** [comment]
I do use two directories.

**Comment by ZhouHansen** [comment]
@austinfrey Thanks! It works after I start another two directories, There may be a hyperdrive instance remained, because I tried this in the same directories before. But why it not clear the instance automatically..

**Comment by austinfrey** [comment]
@ZhouHansen since it could be persisting a lot of data to disk, you might not want to start a replication fresh every time, so it's nice that it doesn't delete the old hyperdrive to create a new one each time. this way you can pick up replication where you left off if you restart your client or server.
