### ISSUE TITLE
downloading twice never calls download callback

### ISSUE THREAD

**Issue by karissa** [mafintosh/hyperdrive#24]
Create an archive and download the contents successfully, then exit the process. Then, run it again. You'll notice that the callback is never fired to finish the download. Example:

```
$ dat dat://.....
Download complete, etc.
^C
$ dat dat://
Connected to 1/1 peers
```

'download complete' never fires because the callback isn't called.

**Comment by mafintosh** [comment]
fixed in https://github.com/mafintosh/hyperdrive/commit/0c363e0f1845361c9d0ec118b99f06b30e06b132
