### ISSUE TITLE
Empty files aren't downloaded

### ISSUE THREAD

**Issue by joehand** [mafintosh/hyperdrive#28]
Empty files get added to metadata but never get transferred or downloaded.

Reproduce:
- Run `dat link` in dat tests fixtures folder (with empty.txt)
- Download the dat link to another folder.
- folder and empty.txt are missing but metadata gets read (they appear in `createEntryStream`)

**Comment by mafintosh** [comment]
we need to create an empty file here instead of returning right away to fix this, https://github.com/mafintosh/hyperdrive/blob/master/index.js#L159

**Comment by joehand** [comment]
Fixed in 3.3.1

**Comment by joehand** [comment]
Same issue as before. They are added to metadata but never get created.

**Comment by mafintosh** [comment]
We should add a test for this then

**Comment by clkao** [comment]
It seems [archive.download](https://github.com/mafintosh/hyperdrive/blob/master/archive.js#L352) needs to special case where `start == end`.  I tried simply doing:
```
        self.options.storage.openAppend(entry.name, true)
        self.options.storage.closeAppend(cb)
```

but that doesn't seem to work as raf thinks it's noop.
