### ISSUE TITLE
max's list of hyperdrive feature requests

### ISSUE THREAD

**Issue by maxogden** [mafintosh/hyperdrive#29]
- [x] download a single file by filename randomly
- [x] upload progress (for showing total amount downloaded, total amount uploaded when sharing)
- [ ] allow string or buffer as the hex link
- [x] use catfile for storage/decouple filesystem
- [ ] fix performance bottleneck on large dats
- [ ] switch from index-at-end to index-on-chunk
- [ ] add digest block to end that has total size + file count
- [ ] dont expose hash to swarm (only share hash of hash etc)
- [ ] remove the drive.add stats object

**Comment by karissa** [comment]
started  #31  for the first bullet
