### ISSUE TITLE
Describe protocol in implementation-agnostic way

### ISSUE THREAD

**Issue by cloudspeech** [mafintosh/hyperdrive#3]
Hi,

As discussed in dotJS, I'd really like to see a protocol specification for HyperDrive. Bonus points for it containing a comparison to wellknown protocols in the same space (BitTorrent?), key assumptions behind it, novel and old use cases where the new protocol would excel (mobile networks?).

Cheers, Markus

**Comment by mafintosh** [comment]
Hi Markus

I've started documenting the specification for hyperdrive here, https://github.com/mafintosh/hyperdrive/blob/master/SPECIFICATION.md. So far only the wire protocol is fully documented but the rest should be online soon.

Among other things its gonna include a comparison to BT as well.

/m

**Comment by mafintosh** [comment]
spec is done :)

**Comment by cloudspeech** [comment]
Am 30.12.2015 um 21:46 schrieb Mathias Buus <notifications@github.com>:

> spec is done :)
> 
> 

Thanks a lot! Looks good, will study in detail later and comment if necessary.

—Markus
