### ISSUE TITLE
Confusing behavior when a relative path is passed into appendFile

### ISSUE THREAD

**Issue by paulkernfeld** [mafintosh/hyperdrive#36]
In the code below, the callback is never called. I don't think that hyperdrive necessarily needs to support relative paths, but either way the callback should definitely be called.

```
var memdb = require('memdb')
var os = require('os')
var hyperdrive = require('hyperdrive')

var drive = hyperdrive(memdb())
var tmpDir = os.tmpdir()
var archive = drive.add(tmpDir)
archive.appendFile('./README.md', console.log)
```

I added a test that shows this behavior, [here](https://github.com/paulkernfeld/hyperdrive/tree/relative-filename).

**Comment by paulkernfeld** [comment]
I think that this applies to the example code in the README.

**Comment by mafintosh** [comment]
fixed in 8 by not having .append anymore hehe
