### ISSUE TITLE
NAT traversal botheration in example code

### ISSUE THREAD

**Issue by paulkernfeld** [mafintosh/hyperdrive#37]
I'm not sure if this is that important, but I'm finding it hard to get the README example running because it requires NAT traversal. It works fine if I modify it to just connect the two hyperdrives directly to each other.

A couple ideas that could solve this:
1. Connect the two hyperdrives together without using discovery-channel, e.g. by printing out the port to connect to.
2. Use webrtc-swarm, which should take advantage of ICE and should always work to let a computer connect to itself, because there will be local ICE candidates.

**Comment by mafintosh** [comment]
We should just switch the readme example to use discovery-swarm instead as that does basic nat hole punching

**Comment by paulkernfeld** [comment]
Hmm, it seems that discovery-swarm isn't fixing the problem for me, although I'm sure that it will help others. I'm guessing this is because I use a VPN. Is there any merit in using webrtc-swarm or another webrtc solution?

**Comment by paulkernfeld** [comment]
Oh, I forgot that it's often hard to install node-webrtc. That probably makes webrtc-swarm less attractive for an example.

**Comment by mafintosh** [comment]
you need to use our dns server which also acts a stun server.
try setting the servers from this gist, https://github.com/datproject/docs/blob/master/diy-dat.md and see if that helps

**Comment by paulkernfeld** [comment]
By now, perhaps electron-webrtc is mature enough so that we could use webrtc-swarm? Either way, this doesn't seem to be a big deal.
