### ISSUE TITLE
mkdirp EEXIST error with long path

### ISSUE THREAD

**Issue by maxogden** [mafintosh/hyperdrive#42]
I added a node_modules folder to hyperdrive. but now i get this error (in electron):

```
Error: EEXIST: file already exists, mkdir '/Users/max/Desktop/electron/node_modules/lightning-image-poly/node_modules/brfs/node_modules/static-module/node_modules/static-eval/node_modules/escodegen/node_modules/.bin/esvalidate'
    at Error (native)
```

which came from this line: https://github.com/mafintosh/hyperdrive/blob/73425f4665045a3092be37adbbc4ab5eef557e90/index.js#L231

I checked it out and other paths < 184 chars long worked. not sure if this path being 184 chars long is what caused it

**Comment by mafintosh** [comment]
this might be related to the fact that, that file is probably a symlink. i'll investigate

**Comment by mafintosh** [comment]
fixed in 8 by a more low level api hehe
