### ISSUE TITLE
archive.list() doesnt callback

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/hyperdrive#54]
I'm getting some inconsistent behaviors from `list()`. Maybe my usage is wrong.

Here's what I'm doing:

``` js
import hyperdrive from 'hyperdrive'
import memdb from 'memdb'
import swarm from 'hyperdrive-archive-swarm'

var drive = hyperdrive(memdb())

function fetch (archiveKey, path) {
  // assume `archiveKey` is a valid key

  // start searching the network
  log('[DAT] Swarming archive', archiveKey)
  var archive = drive.createArchive(archiveKey)
  var sw = swarm(archive)

  // wait for a peer
  sw.once('peer', function (peer) {
    log('[DAT] Swarm peer:', peer, '('+archiveKey+')')

    // list archive contents
    log('[DAT] attempting to list archive')
    archive.list((err, entries) => {
      log('[DAT] list() results', err, entries)
    })
  })
}
```

What I'm seeing is, the 'list() results' log isnt ever happening. (I had it work a couple times, but it hasn't since.)

Any ideas? hyperdrive@6.0.1, hyperdrive-archive-swarm@1.0.2

**Comment by pfraze** [comment]
I think this may be a race. If I update hyperdrive-archive-swarm as thus...

```js
var ds = discoverySwarm(swarmDefaults({
  stream: peer => {
    emitter.emit('peer', peer)
    console.log('replicate') // <-- my addition
    return archive.replicate()
  }
}, opts))
ds.once('listening', () => ds.join(swarmKey))
ds.listen(0)
```

Then it seems to consistently work. If there are multiple threads involved somewhere, then I'd say it's possible the log() call slows down one of the racing threads enough to make it correct

**Comment by mafintosh** [comment]
trying to fix this now...

**Comment by mafintosh** [comment]
works for me now. if it doesn't for you (after re-installing node_modules) please re-open.

**Comment by pfraze** [comment]
Looks fixed!

**Comment by pfraze** [comment]
Ah shoot, no, I'm still seeing the issue. This might be an issue with discovery.

Both scripts are running on my device. What I see is, the dat-hosting process emits many peer events (which start after I try to open in the other process) but the dat-requesting process doesnt emit any.

But, this is inconsistent. Sometimes I get this bad behavior, and sometimes it works immediately.

**Comment by mafintosh** [comment]
Frh

**Comment by pfraze** [comment]
@mafintosh lmk how I can help debug

**Comment by mafintosh** [comment]
fixed in 8
