### ISSUE TITLE
Implement archive deletion

### ISSUE THREAD

**Issue by somebody1234** [mafintosh/hyperdrive#55]
Not really an issue, more just a reminder/to add to a milestone if hyperdrive ever uses milestones

**Comment by juliangruber** [comment]
that is to delete an archive, right? +1

**Comment by pfraze** [comment]
+1, I'll need this

**Comment by somebody1234** [comment]
It's to delete files, deleting every file probably counts as deleting the archive

**Comment by pfraze** [comment]
I'll need both: delete files (if using the leveldb storage) and delete the metadata feed

**Comment by mafintosh** [comment]
deleting files vs deleteing the archive itself is two very different apis so we should track that using separate issues.

**Comment by pfrazee** [comment]
Bump this and #76. @mafintosh I can PR an implementation if you tell me the protocol effects you want

**Comment by mafintosh** [comment]
deleting an archive is as easy as removing the underlying storage now
