### ISSUE TITLE
Progress Stats for 6

### ISSUE THREAD

**Issue by joehand** [mafintosh/hyperdrive#57]
Total size stats (once finalized):

- [x] Total archive size
- [x] Total archive file count

Progress Stats for Individual File Appends/Downloads:

- [x] Bytes downloaded/uploaded
- [ ] bytes added (?)
- [ ] Bytes total

Returning an object from append/download, like we did before, will work.

Along with [these events](https://github.com/mafintosh/hyperdrive/issues/53), I think thats all we will need for Dat CLI.

**Comment by laurengarcia** [comment]
Is it possible to get progress stats by chunk(s)?

**Comment by mafintosh** [comment]
yea. it already emits `upload`/`download` events when a chunk is uploaded or downloaded.

**Comment by mafintosh** [comment]
Total archive size is available through `archive.content.bytes` after .open. Total *entry* count is available through archive.metadata.blocks. Should I alias these to something nicer or is this ok?

**Comment by joehand** [comment]
I think we are all set here. The last one is bytes added but pending depreciation of archive.append the user will do that themselves.
