### ISSUE TITLE
Add support for Firefox

### ISSUE THREAD

**Issue by Widdershin** [mafintosh/hyperdrive#6]
Visiting https://mafintosh.github.io/hyperdrive/ using Firefox 42.0 on OSX 10.10.5 results in a blank page.

There are no errors logged to the console.

If you could hint at what the problem might be I'd be happy to take a crack at solving it.

**Comment by mafintosh** [comment]
Firefox has webrtc support right?

**Comment by Widdershin** [comment]
Yes indeedy.

**Comment by mafintosh** [comment]
Then its probably just some stupid mistake I did :) I'll try to test it in my firefox myself and see if I can fix it

**Comment by ryanramage** [comment]
Seems the root of the issue is 

    SyntaxError: unreachable code after return statement

Which is found in https://github.com/dominictarr/ltgt fixed here https://github.com/dominictarr/ltgt/commit/1760ca5d9142c54f325fa0aca40e0c41f769da00

published in ltgt@2.1.2

I am working for a PR for level.js which needs to bump its depend to that version

**Comment by mafintosh** [comment]
@ryanramage amazing

**Comment by ryanramage** [comment]
@mafintosh has pushed a new bundle.js so it should be working now in FF

**Comment by mafintosh** [comment]
If the fix for reason doesn't work for you @Widdershin feel free to reopen this issue :)

**Comment by Widdershin** [comment]
Just tested it and it's working now, thanks for the amazing turn-around time :+1: :smiley:

**Comment by karissa** [comment]
woohoo!

**Comment by pguth** [comment]
What a hype! :smiley:  :+1:
