### ISSUE TITLE
[Spec] 16-bit Index block entries too restrictive?

### ISSUE THREAD

**Issue by vsivsi** [mafintosh/hyperdrive#65]
Hi, great work from you and the Dat team on this and all of the other component packages. This is all very promising and already super useful! I've been reviewing everything top-to-bottom, and I've run into one design decision that seems a bit too constraining, even in the near-term, and so in the interest of "future-proofing" the spec a bit, I'd like to initiate a discussion.

The decision is the specific choice of exclusively using 16-bit values to hold the Rabin chunked block sizes in the "Index blocks" to provide seekability within the blocks making up a file's feed. This seems to place a rather artificial 64KB upper limit on the maximum size of any chunk, which for TB-scale files would require they be split into 10s of millions of chunks in the process. The block index alone for such a file would weigh-in at > 20MB. The 16-bit values are probably fine for files up to about 1 GB, but we already routinely handle individual files of 100 GB, with larger ones coming all of the time, and so I'd very interested in increasing the random access granularity and deduplication scale in exchange for somewhat lower overhead and better performance.

I've also been benchmarking streaming GB-scale files into replicated NoSQL databases (MongoDB and RethinkDB) using your Rabin chunking and content-addressable indexes, and I'm finding that 20KB mean length chunks are ~2-4x less efficient to store and retrieve (in terms of throughput) when compared to 200KB chunks. From 200KB to ~1MB, the performance benefit of using larger chunks flattens out, but up to that point, the improvement from using larger chunks is substantial.  

Are you open to discussing the possibility of either increasing the block index to use 32-bit values, or alternatively, making the choice of 16/32-bit values an option on a per-file/feed basis? 

Thanks! -Vaughn

**Comment by mafintosh** [comment]
thanks for the detailed issue. latest version (was released last week) has no block size restriction any more. i'll try to update the docs to reflect that asap.

**Comment by mafintosh** [comment]
i'll go into more detail once i get to my laptop on how it currently works here

**Comment by vsivsi** [comment]
Great news!  Thanks!
