### ISSUE TITLE
Hyperdrive Name

### ISSUE THREAD

**Issue by joehand** [mafintosh/hyperdrive#71]
Add hyperdrive name so we can create a download folder with that name. 

``` javascript
 drive.createArchive(key, {
      name: 'my-data-folder'
 }
```

**Comment by karissa** [comment]
would this go into the storage add-on module instead?

**Comment by pfraze** [comment]
I'd like to have this, because names would be much nicer in a UI for listing dats

**Comment by mafintosh** [comment]
supported through the storage name (see readme)
