### ISSUE TITLE
What files does `list` list for a non-live archive?

### ISSUE THREAD

**Issue by paulkernfeld** [mafintosh/hyperdrive#86]
Does the `list` stream end after it's listed all files in the archive? Or does it end after it's listed all files in the local copy? I think it does the second thing, but I was expecting it to do the first one. What do you guys think of updating the behavior of `list` in this case? If not, a clarification in the README would be cool.

**Comment by joehand** [comment]
> Does the list stream end after it's listed all files in the archive?

If you pass option `{live: true}` the list stream *does not* end/callback.

> does it end after it's listed all files in the local copy

It should list all the files in the source metadata, regardless of what is in local copy. I tried a test for this but it was passing. How can I reproduce this?

**Comment by paulkernfeld** [comment]
All right, here's what I'm looking at. I would expect `archive.list` to just hang in this case, because the metadata hasn't been replicated. Instead, it calls the callback. On my machine, this example prints out: `null []`.

```
var crypto = require('crypto')
var memdb = require('memdb')

var hyperdrive = require('.')

var drive = hyperdrive(memdb())
var archive2 = drive.createArchive({key: crypto.randomBytes(32), live: false})
archive2.list(console.log)
```

**Comment by joehand** [comment]
Ya that does sound like a bug but still can't reproduce it. I have this test but it is passing. Is this what you are doing?

```javascript
tape('replicates list', function (t) {
  var drive = hyperdrive(memdb())
  var driveClone = hyperdrive(memdb())

  var archive = drive.createArchive({
    live: false,
    file: function (name) {
      return raf(path.join(__dirname, name))
    }
  })

  archive.append('misc.js')
  archive.append('replicates.js')

  archive.finalize(function (err) {
    t.error(err, 'no error')

    var clone = driveClone.createArchive(archive.key, {live: false})

    clone.list(function (err, entries) {
      t.error(err)
      t.same(entries.length, 2, 'has two entries') // PASSES
      t.end()
    })

    var stream = archive.replicate()
    var streamClone = clone.replicate()

    stream.pipe(streamClone).pipe(stream)
  })
})
```

**Comment by paulkernfeld** [comment]
Ha, I see what's going on now. I thought that I could pass `key` into `drive.createArchive` as a property of `opts`, but that is not allowed! Thanks for taking a look at this!

**Comment by joehand** [comment]
Oh, yep! I missed that in your code too =)
