### ISSUE TITLE
archive.list({live:false}) is confusing when archive.live doesn't match

### ISSUE THREAD

**Issue by joehand** [mafintosh/hyperdrive#88]
The API for `archive.list` is confusing. The live option doesn't follow the `archive.live` option and may not give you what you expect (e.g for `archive.live = false` and `archive.list({live: true})`. 

Possible changes:
1. Rename this option. 
2. End stream if there is a callback present?

**Comment by karissa** [comment]
This came up because @pfraze said he needed to 'be able to take snapshots of the current listing'

one idea:

```js
archive.snapshot(function (link) { 
 archive.list({snapshot: link}) 
})
```

where link is a new hash

**Comment by mafintosh** [comment]
Unlink should call .unlink (if available) on the file object

**Comment by mafintosh** [comment]
Oops commented on the wrong issue. Please ignore

**Comment by mafintosh** [comment]
fixed in 8
