### ISSUE TITLE
Errors trying to sync non-live archives

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/hyperdrive#93]
I create an archive with `dat --snapshot .`, then I try to open it in Beaker with `live` set to undefined in `createArchive`. This gives me the following error:

```
Error: Expected block to be index
  at /Users/paulfrazee/my/beaker-browser/app/node_modules/hyperdrive/archive.js:446:33
```

I'm going to try it with `live` set to false and then comment.

**Comment by pfrazee** [comment]
There's no issue if `live` is explicitly set to false.

**Comment by mafintosh** [comment]
this sounds like an accidental regression that happened since we changed the default value of live.

**Comment by pfrazee** [comment]
Verified resolved 👍
