### ISSUE TITLE
Read file without downloading; or, check if file is downloaded before trying to read

### ISSUE THREAD

**Issue by pfrazee** [mafintosh/hyperdrive#97]
As I understand it, the hyperdrive archive.createFileReadStream will try to download a file before serving it, if it's not already available. Is there a way to disable that, or is there a separate function to check if a file is fully downloaded?

This might be related to the download-progress PRs.

**Comment by pfrazee** [comment]
Here's the method I use to check if the file is downloaded:

```js
function isEntryDownloaded (archive, entry) {
  var offset = entry.content.blockOffset
  for (var i=0; i < entry.blocks; i++) {
    if (!archive.content.has(i + offset))
      return false
  }
  return true
}
```

Pretty simple; I bet we could add that to the archive API

**Comment by mafintosh** [comment]
@pfrazee PR me
